default:
  host: ns6623384.ip-151-80-105.eu
  port: 8081
  dbname: enedisprev
  user: ds_test
  password: ds_test_2020!
production:
  host: ns6623384.ip-151-80-105.eu
  port: 8081
  dbname: enedisprev
  user: ds_test
  password: ds_test_2020!
